import type { MockIncident } from './types'

// Static sample data — real incidents come from Firestore once the map/data
// layer is built. Shared between ActiveIncidentsPanel and SeverityLegend so
// the severity counts and the incident list always agree with each other.
export const MOCK_INCIDENTS: MockIncident[] = [
  {
    id: 'INC-0428',
    title: 'Ridge Rd, 3 km NE of Broadford',
    latitude: -37.18,
    longitude: 145.08,
    severity: 4,
    tag: 'CAT',
    timeAgo: '6m ago',
    confidence: 92,
    status: 'AWAITING',
  },
  {
    id: 'INC-0431',
    title: 'Simmons Creek Track',
    latitude: -37.195,
    longitude: 145.095,
    severity: 3,
    tag: 'EXT',
    timeAgo: '21m ago',
    confidence: 88,
    status: 'AWAITING',
  },
  {
    id: 'INC-0426',
    title: 'Warrandale Rd culvert',
    latitude: -37.205,
    longitude: 145.11,
    severity: 3,
    tag: 'EXT',
    timeAgo: '37m ago',
    confidence: 71,
    status: 'AWAITING',
  },
  {
    id: 'INC-0419',
    title: 'Kinglake NP eastern boundary',
    latitude: -37.55,
    longitude: 145.34,
    severity: 2,
    tag: 'HIGH',
    timeAgo: '1h ago',
    confidence: 90,
    status: 'AWAITING',
  },
  {
    id: 'INC-0402',
    title: 'Old Mill Reserve',
    latitude: -37.545,
    longitude: 145.325,
    severity: 1,
    tag: 'MOD',
    timeAgo: '1h 28m ago',
    confidence: 94,
    status: 'AWAITING',
  },
  {
    id: 'INC-0433',
    title: 'Unnamed track, Bellbird Gully',
    latitude: -37.60,
    longitude: 145.40,
    severity: 1,
    tag: 'REVIEW',
    timeAgo: '2m ago',
    confidence: 34,
    status: 'REVIEW',
  },
  {
    id: 'INC-0435',
    title: 'Broadmeadow fire trail',
    latitude: -37.605,
    longitude: 145.41,
    severity: 1,
    tag: 'REVIEW',
    timeAgo: '4m ago',
    confidence: 41,
    status: 'REVIEW',
  },
]
